language: php
sudo: false
php:
  - 7.3
addons:
  ssh_known_hosts: github.com
before_script:
  # 直近で成功したときのpipバージョンに合わせる
  - /usr/bin/python -m pip install pip==19.0.3
  - cd admin
stages:
  - deploy
jobs:
  include:
    - stage: deploy
      name: "Deploy App"
      script:
        # 以下は失敗する。0.16.4.9 にすると成功となる
        - pip install python-apt==1.1.0b1+ubuntu0.16.4.2
